export const seedProducts = [
  {
    id: 1,
    name: 'Café Santos Bourbon',
    description: 'Notas de chocolate e caramelo, corpo aveludado.',
    price: 42.9,
    image:
      'https://images.unsplash.com/photo-1700353763351-cb61036f3232?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHw1fHxicmF6aWxpYW4lMjBjb2ZmZWUlMjBiZWFuc3xlbnwxfHx8fDE3NzcyOTQ1OTV8MA&ixlib=rb-4.1.0&q=80&w=1080',
    origin: 'Minas Gerais',
    roast: 'Médio',
    rating: 4.8,
    weight: '250g',
    notes: ['Chocolate', 'Caramelo', 'Nozes'],
    featured: 1,
  },
  {
    id: 2,
    name: 'Café Cerrado Mineiro',
    description: 'Acidez cítrica equilibrada com notas de frutas vermelhas.',
    price: 38.9,
    image:
      'https://images.unsplash.com/photo-1708362524830-989c281f5159?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwyfHxicmF6aWxpYW4lMjBjb2ZmZWUlMjBiZWFuc3xlbnwxfHx8fDE3NzcyOTQ1OTV8MA&ixlib=rb-4.1.0&q=80&w=1080',
    origin: 'Cerrado Mineiro',
    roast: 'Claro',
    rating: 4.6,
    weight: '250g',
    notes: ['Frutas vermelhas', 'Cítrico', 'Floral'],
    featured: 0,
  },
  {
    id: 3,
    name: 'Café Mogiana Premium',
    description: 'Blend intenso e encorpado com notas de cacau.',
    price: 45.9,
    image:
      'https://images.unsplash.com/photo-1512372388054-a322888e67a6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwzfHxicmF6aWxpYW4lMjBjb2ZmZWUlMjBiZWFuc3xlbnwxfHx8fDE3NzcyOTQ1OTV8MA&ixlib=rb-4.1.0&q=80&w=1080',
    origin: 'Mogiana Paulista',
    roast: 'Escuro',
    rating: 4.9,
    weight: '250g',
    notes: ['Cacau', 'Especiarias', 'Açúcar mascavo'],
    featured: 1,
  },
  {
    id: 4,
    name: 'Café Mantiqueira Especial',
    description: 'Doce e suave, com mel e amêndoas na xícara.',
    price: 39.9,
    image:
      'https://images.unsplash.com/photo-1673534380559-c6352dd7317d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHw0fHxicmF6aWxpYW4lMjBjb2ZmZWUlMjBiZWFuc3xlbnwxfHx8fDE3NzcyOTQ1OTV8MA&ixlib=rb-4.1.0&q=80&w=1080',
    origin: 'Serra da Mantiqueira',
    roast: 'Médio',
    rating: 4.7,
    weight: '250g',
    notes: ['Mel', 'Amêndoas', 'Baunilha'],
    featured: 0,
  },
  {
    id: 5,
    name: 'Café Bahia Orgânico',
    description: 'Cultivo sustentável com perfil floral e cítrico.',
    price: 48.9,
    image:
      'https://images.unsplash.com/photo-1626379907480-29d844d603ca?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxicmF6aWxpYW4lMjBjb2ZmZWUlMjBiZWFuc3xlbnwxfHx8fDE3NzcyOTQ1OTV8MA&ixlib=rb-4.1.0&q=80&w=1080',
    origin: 'Chapada Diamantina',
    roast: 'Claro',
    rating: 4.8,
    weight: '250g',
    notes: ['Floral', 'Limão', 'Mel'],
    featured: 1,
  },
  {
    id: 6,
    name: 'Café Sul de Minas',
    description: 'Tradicional brasileiro de sabor marcante e equilibrado.',
    price: 35.9,
    image:
      'https://images.unsplash.com/photo-1580933073521-dc49ac0d4e6a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHw3fHxicmF6aWxpYW4lMjBjb2ZmZWUlMjBiZWFuc3xlbnwxfHx8fDE3NzcyOTQ1OTV8MA&ixlib=rb-4.1.0&q=80&w=1080',
    origin: 'Sul de Minas',
    roast: 'Médio',
    rating: 4.5,
    weight: '250g',
    notes: ['Caramelo', 'Nozes', 'Chocolate'],
    featured: 0,
  },
  {
    id: 7,
    name: 'Café Espírito Santo',
    description: 'Aromático e consistente para a rotina do dia a dia.',
    price: 36.9,
    image:
      'https://images.unsplash.com/photo-1549883498-9c1eb45b3cae?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHw4fHxicmF6aWxpYW4lMjBjb2ZmZWUlMjBiZWFuc3xlbnwxfHx8fDE3NzcyOTQ1OTV8MA&ixlib=rb-4.1.0&q=80&w=1080',
    origin: 'Espírito Santo',
    roast: 'Médio',
    rating: 4.6,
    weight: '250g',
    notes: ['Caramelo', 'Frutas secas', 'Mel'],
    featured: 0,
  },
  {
    id: 8,
    name: 'Café Paraná Gourmet',
    description: 'Lote sofisticado com final longo e notas complexas.',
    price: 52.9,
    image:
      'https://images.unsplash.com/photo-1649815511802-f60bd3784493?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHw2fHxicmF6aWxpYW4lMjBjb2ZmZWUlMjBiZWFuc3xlbnwxfHx8fDE3NzcyOTQ1OTV8MA&ixlib=rb-4.1.0&q=80&w=1080',
    origin: 'Norte do Paraná',
    roast: 'Escuro',
    rating: 4.9,
    weight: '250g',
    notes: ['Chocolate amargo', 'Especiarias', 'Frutas vermelhas'],
    featured: 1,
  },
];
